# -*- coding: utf-8 -*-
"""Inst 326 project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RRY20OZnUfhwOXp6JXH2hDmkx62fx89a
"""

import re 
import requests
import json 
import tkinter as tk

#try this address 101 Halpine Road Rockville MD

api_key = 'AIzaSyAPrM0MRPX0xq7yUuF94oot5EkcKT8iuCc'

def get_results(api_key):
  #print(api_key)
  get_address = input('Please enter the address you would like to get delievered to: ' ) 
  separate = re.findall(r'(\d+\s.*)\s(\w+)\s([A-Z]{2})',get_address)
  
  street_info = list(separate[0][0].split(' '))
  house_number = street_info[0]
  street_name = street_info[1]
  street_suffix = street_info[2]
  city_name = separate[0][1]
  state_name = separate[0][2]
  

  #print(house_number)
  #print(street_name)
  #print(street_suffix)



  url_get_att = 'https://maps.googleapis.com/maps/api/geocode/json?address='+house_number+street_name+street_suffix+','+city_name+','+state_name+'&key='+api_key

  print(url_get_att)

#---------------------------------------------------------------
  response = requests.get(url_get_att)
  data = json.loads(response.text)

  get_cords = data['results'][0]['geometry']['location']
  get_lat = get_cords['lat']
  get_lng = get_cords['lng']
 
  #print(get_lat,get_lng)

#---------------------------------------------------------------
#get restaurants near  address location 
#type can be changed 
#keyword is what type of food you want 
  type_place = input ('enter restaurant, hardware, grocery, etc: ')
  type_of_food = input('What type of food you want? For example, enter Japanese, American, Mexican etc: ')
  get_restaurants = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location='+str(get_lat)+','+str(get_lng)+'&radius=5500&type='+type_place+'&keyword='+type_of_food+'&key='+api_key
  
  response_two = requests.get(get_restaurants)
  data_two = json.loads(response_two.text)
  print(get_restaurants)
  names = []
  for i in data_two['results']:
    
    names.append(i['name'])
  #print(names)
  #print(access_name)
  
  app = tk.Tk()

  app.geometry('1000x1000')

  variable = tk.StringVar(app)
  variable.set(names[0])

  opt = tk.OptionMenu(app, variable, *names)
  opt.config(width=90, font=('Helvetica', 12))
  opt.pack()

  app.mainloop()
  #use for origin and desitination place
  #https://maps.googleapis.com/maps/api/directions/json?origin=place_id:ChIJ685WIFYViEgRHlHvBbiD5nE&destination=place_id:ChIJA01I-8YVhkgRGJb0fW4UX7Y&key=AIzaSyAPrM0MRPX0xq7yUuF94oot5EkcKT8iuCc


if __name__ == "__main__":
  api_key = 'AIzaSyAPrM0MRPX0xq7yUuF94oot5EkcKT8iuCc'
  get_results(api_key)